#!/usr/bin/env bash

set -e

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

. /usr/unifi/functions

log 'Run fake 9080 server in background'

# Run a loop in the background
(
    until $(which java) /unifi/init.d/SimpleHttpServer.java; do
        log "Server crashed with exit code $?. Respawning..."
        sleep 2
    done
) &
